# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171120_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='groups_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
